@base = http://localhost:8080

### Request 1
GET {{base}}/patients


### Request 2
GET {{base}}/Patient
    ?_has:Observation:patient:code=55284-4
    &_elements=id

### Request 3
GET {{base}}/Observation
    ?subject=8bfc938e-7836-4e96-b0d8-92756601e0b5
    &_elements=id,code,value
    &code=55284-4