@base = https://server.fire.ly/r4

### Request 1
GET {{base}}/Patient?name=smith
Accept: application/fhir+json

### Request 2
GET {{base}}/Patient?name=smith
    ?_has:Observation:patient:code=55284-4
    

### Request 3
GET {{base}}/Observation
    ?subject=8bfc938e-7836-4e96-b0d8-92756601e0b5
    &_elements=id,code,value
    &code=55284-4

### Request 4
 GET {{base}}/Group/GRP000111

### Request 4
GET {{base}}/Group/GRP000111/$export?_type=Person
Prefer: respond-async
Accept: application/fhir+json


### r
GET https://server.fire.ly/r4/$exportstatus?_id=174f29ef-deb4-42cb-801e-3f11f39d034c


