@base = http://localhost:8080

### Request 1
GET {{base}}/patients


### Request 2
GET {{base}}/patients
    ?birthdate=1985-05-10

### Request 2
GET {{base}}/patients
    ?birthdate=ge1985-05-08
    &family=Davis

### Request 2
GET {{base}}/patients
    ?birthdate=1985-05-10
    &family=Tommy


### Request 2
GET {{base}}/patients
    ?family=Davis

    

### Request 2
GET {{base}}/patients
    ?given=Henk

### Request 2
GET {{base}}/patients
    ?family=Hetty


### Request 2
GET {{base}}/patients
    ?birthdate=1990-01-02
    &family=Hetty

### Request 2
GET {{base}}/patients
    ?birthdate=ge1985-05-10    

### Request 2
GET {{base}}/patients
    ?given=Henk    


### Request 2
GET {{base}}/patients
    ?given=Tommy  


### Request 3
GET {{base}}/Observation
    ?su
    &_elements=id,code,value
    &code=55284-4